export const MarketPlaceABI = [
  {
    type: 'function',
    name: 'buyMineNFT',
    inputs: [
      { name: '_serialId', type: 'uint256', internalType: 'uint256' },
      { name: '_orderId', type: 'uint256', internalType: 'uint256' },
      { name: '_merkleProof', type: 'bytes32[]', internalType: 'bytes32[]' },
      { name: 'signature', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'claimFromCustody',
    inputs: [
      { name: '_serialId', type: 'uint256', internalType: 'uint256' },
      { name: '_tokenId', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'custodyInfoMap',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [
      { name: 'lastCustodyAt', type: 'uint256', internalType: 'uint256' },
      { name: 'totalCustodyTime', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'initialize',
    inputs: [{ name: '_many', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'many',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IMany' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'mineNFTCustodyMap',
    inputs: [
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'paused',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'putIntoCustody',
    inputs: [
      { name: '_serialId', type: 'uint256', internalType: 'uint256' },
      { name: '_tokenId', type: 'uint256', internalType: 'uint256' },
      { name: '_recipient', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'recycle',
    inputs: [
      { name: '_serialId', type: 'uint256', internalType: 'uint256' },
      { name: '_tokenId', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  { type: 'function', name: 'renounceOwnership', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  {
    type: 'function',
    name: 'rescue',
    inputs: [
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'token', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'serialIdPriceMap',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'setPauseStatus',
    inputs: [{ name: 'pauseSatus', type: 'bool', internalType: 'bool' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateSerialPrice',
    inputs: [
      { name: '_serialId', type: 'uint256', internalType: 'uint256' },
      { name: '_price', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'BuyMineNFT',
    inputs: [
      { name: 'account', type: 'address', indexed: true, internalType: 'address' },
      { name: 'serialId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'orderId', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ClaimFromCustody',
    inputs: [
      { name: 'account', type: 'address', indexed: true, internalType: 'address' },
      { name: 'serialId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Initialize',
    inputs: [{ name: 'many', type: 'address', indexed: true, internalType: 'address' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      { name: 'previousOwner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'newOwner', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Paused',
    inputs: [{ name: 'account', type: 'address', indexed: false, internalType: 'address' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PutIntoCustody',
    inputs: [
      { name: 'account', type: 'address', indexed: true, internalType: 'address' },
      { name: 'serialId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'recipient', type: 'address', indexed: false, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RecycleMineNFT',
    inputs: [
      { name: 'account', type: 'address', indexed: true, internalType: 'address' },
      { name: 'serialId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Rescue',
    inputs: [
      { name: 'to', type: 'address', indexed: false, internalType: 'address' },
      { name: 'token', type: 'address', indexed: false, internalType: 'address' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SetPauseStatus',
    inputs: [{ name: 'status', type: 'bool', indexed: false, internalType: 'bool' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Unpaused',
    inputs: [{ name: 'account', type: 'address', indexed: false, internalType: 'address' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'UpdateSerialPrice',
    inputs: [
      { name: 'serialId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'price', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'BlockingAccount', inputs: [{ name: '', type: 'address', internalType: 'address' }] },
  { type: 'error', name: 'ECDSAInvalidSignature', inputs: [] },
  {
    type: 'error',
    name: 'ECDSAInvalidSignatureLength',
    inputs: [{ name: 'length', type: 'uint256', internalType: 'uint256' }],
  },
  { type: 'error', name: 'ECDSAInvalidSignatureS', inputs: [{ name: 's', type: 'bytes32', internalType: 'bytes32' }] },
  { type: 'error', name: 'EnforcedPause', inputs: [] },
  { type: 'error', name: 'ExpectedPause', inputs: [] },
  { type: 'error', name: 'InvaildMerkleProof', inputs: [] },
  {
    type: 'error',
    name: 'InvaildSigner',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'address', internalType: 'address' },
    ],
  },
  { type: 'error', name: 'InvalidOrderId', inputs: [{ name: 'orderId', type: 'uint256', internalType: 'uint256' }] },
  { type: 'error', name: 'NotEnoughEth', inputs: [] },
  {
    type: 'error',
    name: 'NotOwner',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'address', internalType: 'address' },
    ],
  },
  { type: 'error', name: 'OwnableInvalidOwner', inputs: [{ name: 'owner', type: 'address', internalType: 'address' }] },
  {
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
  },
  { type: 'error', name: 'TransferFailed', inputs: [] },
];
